#-------------------------------
# General Site Settings

menu:
- {name: 'About', url: 'pages/about.html'}
- {name: 'Projects', url: ''}
# - {name: 'Resume', url: 'pages/resume.html'}

- {name: 'Resume', url: "pages/artia_resume.pdf"}

- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  Hi! I am a Graduate student at the Robotics Institute in Carnegie Mellon University, pursuing my Master's in Robotic Systems Development. Currently, I am working with Prof. Howie Choset to develop a robotic surgical system to autonomously localize tumors of the liver, and display their positions in real-time using augmented reality. 

  My most recent work experience was at Johnson & Johnson, in the Robotics & Digital Surgery group where I defined functional requirements for a robot arm to perform manipulation tasks, and also automated the testing of critical robotic faults.

  In the past, I have had the opportunity to spend two summers interning at Robert Bosch Manufacturing solutions GmbH where I programmed collaborative robots to perform specific tasks to meet end-user requirements.

  Within the robotics domain, my areas of interest are motion planning, optimal control, spatial kinematics, state estimation, rigid body transformations, and point-cloud registration techniques. I strive to leverage my technical skills to enhance the healthcare experience through medical and surgical robotic solutions. 


# I'm Arti, and I'm currently pursuing my Master's in Robotics Systems Development at Carnegie Mellon Univeristy. My primary areas of interest are motion planning, robot controls, spatial kinematics etc.

contact: >
  # Contact

  Thank you for stopping by! If you would like to discuss my work further, please reach out to me at [artia@andrew.cmu.edu](mailto:artia@andrew.cmu.edu).
  
#-------------------------------
# Work Section

resume: >
  # Resume
  

projects:
- {name: 'Augmented Reality for Minimally Invasive Surgery', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Robotic Bin Picking', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: '3D Dense Reconstruction using ICP and Point-based Fusion', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Path Planning on Constraint Manifolds', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Spatial Kinematics of a 7-DoF Robotic Arm', folder: 'proj-5', file: 'projects/proj-5.html'}
- {name: 'Extended Kalman Filter for 2D SLAM', folder: 'proj-6', file: 'projects/proj-6.html'}
- {name: 'Control and Trajectory Generation of a Quadcopter', folder: 'proj-7', file: 'projects/proj-7.html'}
- {name: 'Object Tracking', folder: 'proj-8', file: 'projects/proj-8.html'}
- {name: 'Planar Homography', folder: 'proj-9', file: 'projects/proj-9.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/ArtiAnantharaman'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/arti-anantharaman'}
- {icon: 'envelope', link: 'mailto:artia@andrew.cmu.edu'}


